In [1]:
import tensorflow as tf
# from tensorflow.examples.tutorials.mnist import input_data
# mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)


# v=mnist.train.num_examples
# v

/home/david/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/david/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/david/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/david/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.

In [13]:
x = tf.placeholder('float',[None,2,4,])
#print(x)

with tf.Session() as sess:
    y= [[[1,2,4,5],
         [1,2,3,4]],[[4,6,2,5],
                   [3,4,5,6]]]
    t = sess.run(x,feed_dict={x:y})
print(t)
x = tf.transpose(t)
print(x)
x = tf.transpose(t,[1,0,2])
print(x)





[[[1. 2. 4. 5.]
  [1. 2. 3. 4.]]

 [[4. 6. 2. 5.]
  [3. 4. 5. 6.]]]
Tensor("transpose_3:0", shape=(4, 2, 2), dtype=float32)
Tensor("transpose_4:0", shape=(2, 2, 4), dtype=float32)


In [3]:
# from collections import Counter
# empty=[]
# x = [2,4,5]
# y=[6,4,8]
# s = empty+x+y
# v=Counter(s)
# v
# for z in v:
#     print(v[z])
    

In [10]:
import numpy as np

x = np.ones((1,2,3))
#print(x)
#print(np.transpose(x))
n=np.transpose(x,(1,0,2))
print(n)             
n.shape    

[[[1. 1. 1.]]

 [[1. 1. 1.]]]


(2, 1, 3)

In [7]:
data = np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0])
x=data.reshape((2,5,1))
x

array([[[0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5]],

       [[0.6],
        [0.7],
        [0.8],
        [0.9],
        [1. ]]])